In [1]:
# Importing Libraries
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter("ignore")


In [144]:
## Load Dataset
df = pd.read_excel('red.xlsx')
df.head()


Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567      3.0 2022-02-02   
1         y 2022-02-01  1234568  445931234568      0.0 2022-02-02   
2         n 2022-02-01  1234569  445931234569      NaN 2022-02-02   
3         y 2022-02-01  1234567  445931234567      2.0 2022-02-02   
4         y 2022-02-02  1234567  445941234567      2.0 2022-02-03   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      3.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
2  445941234569      NaN 2022-02-03  445951234569      NaN  
3  445941234567      3.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0

In [145]:
df = df.loc[df['Condition'] == 'y']
df.head(10)


Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567      3.0 2022-02-02   
1         y 2022-02-01  1234568  445931234568      0.0 2022-02-02   
3         y 2022-02-01  1234567  445931234567      2.0 2022-02-02   
4         y 2022-02-02  1234567  445941234567      2.0 2022-02-03   
5         y 2022-02-02  1234567  445941234567      1.0 2022-02-03   
7         y 2022-02-01  1234567  445931234567      1.0 2022-02-02   
8         y 2022-02-01  1234567  445931234567      0.0 2022-02-02   
9         y 2022-02-02  1234567  445941234567      0.0 2022-02-03   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      3.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
3  445941234567      3.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0  
5  445951234567      1.0 2022-02-04  445961234567      0.0  
7  445941234567      1.0 2022-02-03  445951234567      0.0  
8  445941234567      1.0 2022-02-03  445951234567      0.0  
9         44595      0.0 2022-02-04  445961234567      0.0

In [178]:
x = np.array(df['dateId'])
x

array([445931234567, 445931234568, 445931234567, 445941234567,
       445941234567, 445931234567, 445931234567, 445941234567])

In [147]:
for i in range(len(x)):
    for j  in range(i+1,len(x)):
        # if x[i]==x[j]:
            print(i,j)

0 1
0 2
0 3
0 4
0 5
0 6
0 7
1 2
1 3
1 4
1 5
1 6
1 7
2 3
2 4
2 5
2 6
2 7
3 4
3 5
3 6
3 7
4 5
4 6
4 7
5 6
5 7
6 7


In [138]:
x[2]

445931234567

In [179]:
for i in range(len(x)):
    for j  in range(i+1,len(x)):
        if x[i]==x[j]:
            print(i,j,x[i])

0 2 445931234567
0 5 445931234567
0 6 445931234567
2 5 445931234567
2 6 445931234567
3 4 445941234567
3 7 445941234567
4 7 445941234567
5 6 445931234567


In [194]:
y = df['dateId'].value_counts()
y

445931234567    4
445941234567    3
445931234568    1
Name: dateId, dtype: int64

In [195]:
type(y)

pandas.core.series.Series

In [196]:
keys = y.keys()
keys

Int64Index([445931234567, 445941234567, 445931234568], dtype='int64')

In [198]:
counter = y.values
counter2 = counter
counter

array([4, 3, 1])

In [183]:
redial =[]
for i in range(len(x)):
    for j  in range(len(counter)):
        if x[i]==keys[j]:
            counter[j]=counter[j]-1
            redial.append(counter[j])
            print(i,j,x[i])

0 0 445931234567
1 2 445931234568
2 0 445931234567
3 1 445941234567
4 1 445941234567
5 0 445931234567
6 0 445931234567
7 1 445941234567


In [184]:
redial

[3, 0, 2, 2, 1, 1, 0, 0]

In [187]:
df.head(10)

Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567        3 2022-02-02   
1         y 2022-02-01  1234568  445931234568        0 2022-02-02   
3         y 2022-02-01  1234567  445931234567        2 2022-02-02   
4         y 2022-02-02  1234567  445941234567        2 2022-02-03   
5         y 2022-02-02  1234567  445941234567        1 2022-02-03   
7         y 2022-02-01  1234567  445931234567        1 2022-02-02   
8         y 2022-02-01  1234567  445931234567        0 2022-02-02   
9         y 2022-02-02  1234567  445941234567        0 2022-02-03   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      3.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
3  445941234567      3.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0  
5  445951234567      1.0 2022-02-04  445961234567      0.0  
7  445941234567      1.0 2022-02-03  445951234567      0.0  
8  445941234567      1.0 2022-02-03  445951234567      0.0  
9         44595      0.0 2022-02-04  445961234567      0.0

In [186]:
df.redial1 = redial

In [190]:

redial3 = []

In [188]:
r = np.array(df['dateId2'])
r

array([445941234567, 445941234568, 445941234567, 445951234567,
       445951234567, 445941234567, 445941234567,        44595])

In [211]:
y

445931234567    4
445941234567    3
445931234568    1
Name: dateId, dtype: int64

In [220]:
a =445941234567
print(a == 445931234567) 
print(a == 445941234567)
print(a  == 445931234568)

False
True
False


In [202]:
counter2

array([4, 3, 1])

In [206]:
redial2 =[0]*len(r)
for i in range(len(r)):
    for j  in range(len(counter2)):
        if r[i]==keys[j]:
            redial2[i]=counter2[j]
            print(i,j,r[i])
redial2

0 1 445941234567
2 1 445941234567
5 1 445941234567
6 1 445941234567


[3, 0, 3, 0, 0, 3, 3, 0]

In [200]:
redial2

[0, 0, 0, 0, 3, 3, 3, 3]

In [223]:
s =np.array(df['dateId3'])
s

array([445951234567, 445951234568, 445951234567, 445961234567,
       445961234567, 445951234567, 445951234567, 445961234567])

In [224]:
counter2

array([4, 3, 1])

In [225]:
keys

Int64Index([445931234567, 445941234567, 445931234568], dtype='int64')

In [234]:
a =445961234567
print(a == 445931234567) 
print(a == 445941234567)
print(a  == 445931234568)

False
False
False


In [222]:
redial3 =[0]*len(s)
for i in range(len(s)):
    for j  in range(len(counter2)):
        if s[i]==keys[j]:
            redial3[i]=counter2[j]
            print(i,j,r[i])
redial3

[0, 0, 0, 0, 0, 0, 0, 0]

In [110]:
x = df['dateId']

In [111]:
from itertools import groupby
counts = [(i, len(list(c))) for i,c in groupby(x)]      # Create value-count pairs as list of tuples 
print(counts)


[(445931234567, 1), (445931234568, 1), (445931234567, 1), (445941234567, 2)]


In [67]:
type(counts)

list

In [68]:
counts = np.array(counts)

In [69]:
for el in counts:
    type(el[1])
    el[1] = el[1] - 1  
    # counts
    print(el[1])



0
0
0
1


In [88]:
type(counts)

numpy.ndarray

In [89]:
counts.shape

(4, 2)

In [90]:
arr1,arr2=np.split(counts,2,axis=1)

In [92]:
arr1,arr2

(array([[445931234567],
        [445931234568],
        [445931234567],
        [445941234567]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [84]:
for j in counts:
    print(j,counts[j][0])

IndexError: index 445931234567 is out of bounds for axis 0 with size 4

In [94]:
df['dateId'][1]

445931234568

In [96]:
len(df['dateId'])

5

In [99]:
type(df['dateId'])

pandas.core.series.Series

In [100]:
dates = np.array(df['dateId'])
type(dates)

numpy.ndarray

In [95]:
for i in len(df['dateId']):
    for j in len(arr1):
        if df['dateId'][i]==arr1[j]:
            print(df['dateId'][i],arr1[j])

TypeError: 'int' object is not iterable

In [105]:
df['dateId'],arr1,arr2

(0    445931234567
 1    445931234568
 3    445931234567
 4    445941234567
 5    445941234567
 Name: dateId, dtype: int64,
 array([[445931234567],
        [445931234568],
        [445931234567],
        [445941234567]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [102]:
c = np.in1d(dates,arr1)
c

array([ True,  True,  True,  True,  True])