In [1]:
# Importing Libraries
import pandas as pd 
import numpy as np
import warnings
warnings.simplefilter("ignore")


In [2]:
## Load Dataset
df = pd.read_excel('red1.xlsx')
df.head()


Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567      1.0 2022-02-02   
1         y 2022-02-01  1234568  445931234568      0.0 2022-02-02   
2         n 2022-02-01  1234569  445931234569      NaN 2022-02-02   
3         y 2022-02-01  1234567  445931234567      0.0 2022-02-02   
4         y 2022-02-02  1234567  445941234567      1.0 2022-02-03   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      2.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
2  445941234569      NaN 2022-02-03  445951234569      NaN  
3  445941234567      2.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0

In [3]:
df_all =df

In [4]:
df = df.loc[df['Condition'] == 'y']
df.head(10)


Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567      1.0 2022-02-02   
1         y 2022-02-01  1234568  445931234568      0.0 2022-02-02   
3         y 2022-02-01  1234567  445931234567      0.0 2022-02-02   
4         y 2022-02-02  1234567  445941234567      1.0 2022-02-03   
5         y 2022-02-02  1234567  445941234567      0.0 2022-02-03   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      2.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
3  445941234567      2.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0  
5  445951234567      1.0 2022-02-04  445961234567      0.0

In [5]:
x = np.array(df_all['dateId'])
x

array([445931234567, 445931234568, 445931234569, 445931234567,
       445941234567, 445941234567, 445951234567])

In [6]:
for i in range(len(x)):
    for j  in range(i+1,len(x)):
        if x[i]==x[j]:
            print(i,j,x[i])

0 3 445931234567
4 5 445941234567


In [7]:
df['dateId'].value_counts()

445931234567    2
445941234567    2
445931234568    1
Name: dateId, dtype: int64

In [8]:
y = df_all['dateId'].value_counts()
y

445931234567    2
445941234567    2
445931234568    1
445931234569    1
445951234567    1
Name: dateId, dtype: int64

In [9]:
keys = y.keys()
keys

Int64Index([445931234567, 445941234567, 445931234568, 445931234569,
            445951234567],
           dtype='int64')

In [10]:
y.values

array([2, 2, 1, 1, 1])

In [11]:
counters = y.values
counter2 = counters
counters

array([2, 2, 1, 1, 1])

In [12]:
c3 =counter2
c3,counter2,counters

(array([2, 2, 1, 1, 1]), array([2, 2, 1, 1, 1]), array([2, 2, 1, 1, 1]))

In [13]:
len(counters)

5

In [14]:
redial =[]
for i in range(len(x)):
    for j  in range(len(counters)):
        if x[i]==keys[j]:
            counters[j]=counters[j]-1
            redial.append(counters[j])
            print(i,j,x[i])

0 0 445931234567
1 2 445931234568
2 3 445931234569
3 0 445931234567
4 1 445941234567
5 1 445941234567
6 4 445951234567


In [15]:
for i in range(len(df_all)):
    if df_all['Condition'][i] == 'n':
        redial[i]= 0

        

In [16]:
redial

[1, 0, 0, 0, 1, 0, 0]

In [17]:
df_all.redial1 = redial

In [18]:
df_all.head(10)

Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567        1 2022-02-02   
1         y 2022-02-01  1234568  445931234568        0 2022-02-02   
2         n 2022-02-01  1234569  445931234569        0 2022-02-02   
3         y 2022-02-01  1234567  445931234567        0 2022-02-02   
4         y 2022-02-02  1234567  445941234567        1 2022-02-03   
5         y 2022-02-02  1234567  445941234567        0 2022-02-03   
6         n 2022-02-03  1234567  445951234567        0 2022-02-04   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567      2.0 2022-02-03  445951234567      1.0  
1  445941234568      0.0 2022-02-03  445951234568      0.0  
2  445941234569      NaN 2022-02-03  445951234569      NaN  
3  445941234567      2.0 2022-02-03  445951234567      1.0  
4  445951234567      1.0 2022-02-04  445961234567      0.0  
5  445951234567      1.0 2022-02-04  445961234567      0.0  
6  445961234567      NaN 2022-02-05  445971234567      NaN

In [19]:
r = np.array(df_all['dateId2'])
r

array([445941234567, 445941234568, 445941234569, 445941234567,
       445951234567, 445951234567, 445961234567])

In [34]:
y = df_all['dateId'].value_counts()
keys = y.keys()
y.values
counter2 = y.values
counter2

array([2, 2, 1, 1, 1])

In [21]:
a =445941234567
print(a == 445931234567) 
print(a == 445941234567)
print(a  == 445931234568)

False
True
False


In [35]:
counter2

array([2, 2, 1, 1, 1])

In [36]:
redial2 =[0]*len(r)
for i in range(len(r)):
    for j  in range(len(counter2)):
        if r[i]==keys[j]:
            redial2[i]=counter2[j]
            print(i,j,r[i])
redial2

0 1 445941234567
3 1 445941234567
4 4 445951234567
5 4 445951234567


[2, 0, 0, 2, 1, 1, 0]

In [37]:
for i in range(len(df_all)):
    if df_all['Condition'][i] == 'n':
        redial2[i]= 0
redial2

[2, 0, 0, 2, 1, 1, 0]

In [38]:
redial2

[2, 0, 0, 2, 1, 1, 0]

In [39]:
s =np.array(df_all['dateId3'])
s

array([445951234567, 445951234568, 445951234569, 445951234567,
       445961234567, 445961234567, 445971234567])

In [40]:
counter2

array([2, 2, 1, 1, 1])

In [28]:
a =445961234567
print(a == 445931234567) 
print(a == 445941234567)
print(a  == 445931234568)

False
False
False


In [41]:
redial3 =[0]*len(s)
for i in range(len(s)):
    for j  in range(len(counter2)):
        if s[i]==keys[j]:
            redial3[i]=counter2[j]
            print(i,j,r[i])
redial3

0 4 445941234567
3 4 445941234567


[1, 0, 0, 1, 0, 0, 0]

In [42]:
for i in range(len(df_all)):
    if df_all['Condition'][i] == 'n':
        redial3[i]= 0
redial3

[1, 0, 0, 1, 0, 0, 0]

In [43]:
df_all['redial2'] = redial2
df_all['redial3'] = redial3
df_all.head(10)

Condition       Date    phone        dateId  redial1    nextDay  \
0         y 2022-02-01  1234567  445931234567        1 2022-02-02   
1         y 2022-02-01  1234568  445931234568        0 2022-02-02   
2         n 2022-02-01  1234569  445931234569        0 2022-02-02   
3         y 2022-02-01  1234567  445931234567        0 2022-02-02   
4         y 2022-02-02  1234567  445941234567        1 2022-02-03   
5         y 2022-02-02  1234567  445941234567        0 2022-02-03   
6         n 2022-02-03  1234567  445951234567        0 2022-02-04   

        dateId2  redial2    twoDays       dateId3  redial3  
0  445941234567        2 2022-02-03  445951234567        1  
1  445941234568        0 2022-02-03  445951234568        0  
2  445941234569        0 2022-02-03  445951234569        0  
3  445941234567        2 2022-02-03  445951234567        1  
4  445951234567        1 2022-02-04  445961234567        0  
5  445951234567        1 2022-02-04  445961234567        0  
6  445961234567        0 2022-02-05  445971234567        0

In [ ]:
# Importing Libraries
import pandas as pd 
import numpy as np
import warnings
warnings.simplefilter("ignore")

## Load Dataset
df = pd.read_excel('red1.xlsx')
df.head()

df_all =df
df = df.loc[df['Condition'] == 'y']
df.head(10)

x = np.array(df_all['dateId'])
