# Numpy

## Import Librarires

In [1]:
!pip install numpy

In [2]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

## 1D Array

In [3]:
a = np.array([1,2,3,4,5,6,7])

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7])

### Zero array

In [15]:
b1 = np.zeros(4)
b1

array([0., 0., 0., 0.])

### Array of 1s

In [7]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

### Empty Array

In [8]:
c = np.empty(4)
c

array([1., 1., 1., 1.])

### Arange

In [10]:
d = np.arange(14)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
e = np.arange(2,14)
e

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
f = np.arange(2,34,3) #with differences
f

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### Linearly Space Arrays

In [17]:
g = np.linspace(0,100 , 6)  #6 is number of elements linearly separated
g

array([  0.,  20.,  40.,  60.,  80., 100.])

### Specific Data type in arrays

In [18]:
h = np.ones(9, dtype=np.int8)
h

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [19]:
i = np.ones(9, dtype=np.float16)
i

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float16)

In [21]:
j = np.ones(9, dtype=np.str_)
j

array(['1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

## 2D Arrays

In [23]:
b1 = np.zeros((4,6))
b1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.empty((3,2))

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

## 3D Array

### Making and Reshaping 3D array

In [31]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
d = np.arange(90).reshape(3,5,6)
d

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])